import type { Inimigo } from './tipos.js';

/*
 * Os inimigos comuns, dois ou três por área.
 *
 * Os números aqui são **proporção entre arquétipos**, não valor final. Quem
 * dá a curva é `run.ts`, com as constantes de balanceamento. Por isso um
 * inimigo da área 5 não tem vida base maior que um da área 1: se tivesse, a
 * progressão seria contada duas vezes — uma na base, outra na escala — e a
 * bancada mostrou exatamente isso, com a luta indo de nove para vinte e cinco
 * segundos ao longo da run. O que muda entre áreas é o **formato**: mais
 * blindado, mais rápido, com golpe especial mais duro. As duas coisas não se confundem.
 *
 * `especial` é o que impede a luta de virar uma troca monótona: um golpe
 * pesado a cada tantos segundos obriga a build a ter alguma resposta —
 * Armadura, cura ou matar antes.
 */

export const INIMIGOS: readonly Inimigo[] = [
  /* ---- Área 1 · Ruínas do Pátio ---------------------------------------- */
  {
    id: 'i-saqueador',
    nome: 'Saqueador',
    porte: 'normal',
    vida: 105,
    armadura: 18,
    dano: 8,
    intervaloS: 1.9,
    exp: 14,
    area: 1,
    silhueta: {
      forma: 'humanoide',
      corpo: '#6b5a3e',
      detalhe: '#a89268',
      brilho: '#d9c48a',
      largura: 18,
      altura: 26,
    },
  },
  {
    id: 'i-lobo-das-ruinas',
    nome: 'Lobo das Ruínas',
    porte: 'normal',
    vida: 86,
    armadura: 6,
    dano: 10,
    intervaloS: 1.4,
    exp: 14,
    area: 1,
    silhueta: {
      forma: 'besta',
      corpo: '#5a5248',
      detalhe: '#8a8073',
      brilho: '#d8d0bf',
      largura: 24,
      altura: 18,
    },
  },
  {
    id: 'i-sentinela-de-pedra',
    nome: 'Sentinela de Pedra',
    porte: 'normal',
    vida: 132,
    armadura: 38,
    dano: 7,
    intervaloS: 2.3,
    exp: 16,
    area: 1,
    especial: { nome: 'Pancada', aCadaS: 7, dano: 16 },
    silhueta: {
      forma: 'construto',
      corpo: '#4f5a4a',
      detalhe: '#75836d',
      brilho: '#a8d86a',
      largura: 20,
      altura: 28,
    },
  },

  /* ---- Área 2 · Catacumbas --------------------------------------------- */
  {
    id: 'i-carniçal',
    nome: 'Carniçal',
    porte: 'normal',
    vida: 104,
    armadura: 14,
    dano: 9,
    intervaloS: 1.6,
    exp: 20,
    area: 2,
    silhueta: {
      forma: 'humanoide',
      corpo: '#5d5468',
      detalhe: '#8b7fa3',
      brilho: '#c9b8e6',
      largura: 18,
      altura: 26,
    },
  },
  {
    id: 'i-lamento',
    nome: 'Lamento',
    porte: 'normal',
    vida: 92,
    armadura: 0,
    dano: 11,
    intervaloS: 1.7,
    exp: 20,
    area: 2,
    especial: { nome: 'Uivo', aCadaS: 8, dano: 17 },
    silhueta: {
      forma: 'espectro',
      corpo: '#463a52',
      detalhe: '#7e6ba0',
      brilho: '#b9a6e0',
      largura: 20,
      altura: 26,
    },
  },
  {
    id: 'i-guarda-ossea',
    nome: 'Guarda Óssea',
    porte: 'normal',
    vida: 138,
    armadura: 40,
    dano: 8,
    intervaloS: 2.1,
    exp: 22,
    area: 2,
    especial: { nome: 'Escudo de Ossos', aCadaS: 9, dano: 14, quebraArmadura: 12 },
    silhueta: {
      forma: 'humanoide',
      corpo: '#7a7264',
      detalhe: '#b3a894',
      brilho: '#e0d6bf',
      largura: 20,
      altura: 27,
    },
  },

  /* ---- Área 3 · Profundezas -------------------------------------------- */
  {
    id: 'i-rastejante',
    nome: 'Rastejante',
    porte: 'normal',
    vida: 98,
    armadura: 12,
    dano: 11,
    intervaloS: 1.4,
    exp: 27,
    area: 3,
    silhueta: {
      forma: 'besta',
      corpo: '#1d4148',
      detalhe: '#3f7d7a',
      brilho: '#5fd9c0',
      largura: 26,
      altura: 18,
    },
  },
  {
    id: 'i-devorador-cego',
    nome: 'Devorador Cego',
    porte: 'normal',
    vida: 122,
    armadura: 24,
    dano: 9,
    intervaloS: 1.8,
    exp: 29,
    area: 3,
    especial: { nome: 'Mordida Funda', aCadaS: 6.5, dano: 19 },
    silhueta: {
      forma: 'aberracao',
      corpo: '#14282b',
      detalhe: '#2f6a63',
      brilho: '#7fe4d2',
      largura: 24,
      altura: 26,
    },
  },
  {
    id: 'i-golem-de-limo',
    nome: 'Golem de Limo',
    porte: 'normal',
    vida: 146,
    armadura: 46,
    dano: 8,
    intervaloS: 2.2,
    exp: 30,
    area: 3,
    silhueta: {
      forma: 'construto',
      corpo: '#22403f',
      detalhe: '#3f7d7a',
      brilho: '#5fd9c0',
      largura: 22,
      altura: 28,
    },
  },

  /* ---- Área 4 · Fortaleza Interior ------------------------------------- */
  {
    id: 'i-lanceiro-de-brasa',
    nome: 'Lanceiro de Brasa',
    porte: 'normal',
    vida: 112,
    armadura: 30,
    dano: 10,
    intervaloS: 1.7,
    exp: 38,
    area: 4,
    silhueta: {
      forma: 'humanoide',
      corpo: '#6b3820',
      detalhe: '#b06a34',
      brilho: '#ffb15e',
      largura: 18,
      altura: 27,
    },
  },
  {
    id: 'i-cao-de-forja',
    nome: 'Cão de Forja',
    porte: 'normal',
    vida: 94,
    armadura: 16,
    dano: 12,
    intervaloS: 1.3,
    exp: 38,
    area: 4,
    especial: { nome: 'Investida', aCadaS: 6, dano: 20 },
    silhueta: {
      forma: 'besta',
      corpo: '#4a2a1c',
      detalhe: '#a3532a',
      brilho: '#ff8c3a',
      largura: 26,
      altura: 19,
    },
  },
  {
    id: 'i-mestre-de-armas',
    nome: 'Mestre de Armas',
    porte: 'normal',
    vida: 150,
    armadura: 52,
    dano: 9,
    intervaloS: 1.9,
    exp: 42,
    area: 4,
    especial: { nome: 'Estocada', aCadaS: 7.5, dano: 18, quebraArmadura: 20 },
    silhueta: {
      forma: 'humanoide',
      corpo: '#33211a',
      detalhe: '#8a4f2c',
      brilho: '#ffc98a',
      largura: 20,
      altura: 28,
    },
  },

  /* ---- Área 5 · Trono Oculto ------------------------------------------- */
  {
    id: 'i-arauto',
    nome: 'Arauto do Trono',
    porte: 'normal',
    vida: 120,
    armadura: 42,
    dano: 11,
    intervaloS: 1.7,
    exp: 52,
    area: 5,
    especial: { nome: 'Decreto', aCadaS: 7, dano: 20 },
    silhueta: {
      forma: 'humanoide',
      corpo: '#4d1030',
      detalhe: '#a32a55',
      brilho: '#ff5f8d',
      largura: 19,
      altura: 28,
    },
  },
  {
    id: 'i-coisa-sem-nome',
    nome: 'Coisa Sem Nome',
    porte: 'normal',
    vida: 104,
    armadura: 18,
    dano: 13,
    intervaloS: 1.5,
    exp: 52,
    area: 5,
    silhueta: {
      forma: 'aberracao',
      corpo: '#1f0d1b',
      detalhe: '#7a1f4e',
      brilho: '#ff3d6e',
      largura: 25,
      altura: 27,
    },
  },
  {
    id: 'i-guarda-do-trono',
    nome: 'Guarda do Trono',
    porte: 'normal',
    vida: 158,
    armadura: 64,
    dano: 10,
    intervaloS: 2,
    exp: 58,
    area: 5,
    especial: { nome: 'Sentença', aCadaS: 8, dano: 22, quebraArmadura: 26 },
    silhueta: {
      forma: 'construto',
      corpo: '#3a0f2c',
      detalhe: '#8a2a55',
      brilho: '#ff85aa',
      largura: 22,
      altura: 29,
    },
  },
];

export const inimigosDaArea = (area: number): readonly Inimigo[] =>
  INIMIGOS.filter((inimigo) => inimigo.area === area);
