/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BadgesUsernameRouteImport } from './routes/badges.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesUsernameRoute = BadgesUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => BadgesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRouteWithChildren
  '/chat': typeof ChatRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/badges/$username': typeof BadgesUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRouteWithChildren
  '/chat': typeof ChatRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/badges/$username': typeof BadgesUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRouteWithChildren
  '/chat': typeof ChatRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/badges/$username': typeof BadgesUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/badges'
    | '/chat'
    | '/ranking'
    | '/reset-password'
    | '/badges/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/badges'
    | '/chat'
    | '/ranking'
    | '/reset-password'
    | '/badges/$username'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/badges'
    | '/chat'
    | '/ranking'
    | '/reset-password'
    | '/badges/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BadgesRoute: typeof BadgesRouteWithChildren
  ChatRoute: typeof ChatRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges/$username': {
      id: '/badges/$username'
      path: '/$username'
      fullPath: '/badges/$username'
      preLoaderRoute: typeof BadgesUsernameRouteImport
      parentRoute: typeof BadgesRoute
    }
  }
}

interface BadgesRouteChildren {
  BadgesUsernameRoute: typeof BadgesUsernameRoute
}

const BadgesRouteChildren: BadgesRouteChildren = {
  BadgesUsernameRoute: BadgesUsernameRoute,
}

const BadgesRouteWithChildren =
  BadgesRoute._addFileChildren(BadgesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BadgesRoute: BadgesRouteWithChildren,
  ChatRoute: ChatRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
